### ISSUE TITLE
Players data

### ISSUE THREAD

**Issue by aliondev** [pabloleonalcaide/ReactJS-Playground-Project#1]
https://github.com/pabloleonalcaide/ReactJS-Playground-Project/blob/master/src/players.js

if you need keys to be numbers you should use an array, however I think you could use the players names (as they are unique) as keys, so you just need to store something like this:

{
      name1: position1,
      name2: position2
...
}

I think you should keep the positions in a separate file and use them as constants because probably you will need to use them several times across the app

**Comment by pabloleonalcaide** [comment]
Thanks, do you think now is better? I'm not sure if files as players.js or positions.js should be in a different route.
